import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Check, Plus, Trash, Image } from '@phosphor-icons/react';
import { websiteContent } from './website.js';

export default function WebsiteEditor({state,onSave,navigate,guard}) {
  const [form,setForm]=useState(()=>structuredClone(websiteContent(state)));
  const saved=useRef(JSON.stringify(websiteContent(state)));
  const [tab,setTab]=useState('identity');
  const [error,setError]=useState('');
  const [message,setMessage]=useState('');
  const dirty=JSON.stringify(form)!==saved.current;
  const current=websiteContent(state);
  useEffect(()=>{guard.current=dirty;return()=>{guard.current=false;};},[dirty,guard]);
  useEffect(()=>{const leave=e=>{if(dirty){e.preventDefault();e.returnValue='';}};addEventListener('beforeunload',leave);return()=>removeEventListener('beforeunload',leave);},[dirty]);
  const set=(key,value)=>{setForm(f=>({...f,[key]:value}));setError('');setMessage('');};
  const field=(key,label,{area=false,max=200,hint='',required=true}={})=><div className="field"><label htmlFor={`site-${key}`}>{label}{required?' *':''}</label>{area?<textarea id={`site-${key}`} rows={3} maxLength={max} value={form[key]} required={required} onChange={e=>set(key,e.target.value)}/>:<input id={`site-${key}`} maxLength={max} value={form[key]} required={required} type={key==='email'?'email':key==='phone'?'tel':'text'} onChange={e=>set(key,e.target.value)}/>} {hint&&<small>{hint}</small>}</div>;
  const upload=async(key,file)=>{if(!file)return;setError('');if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>750000){setError('Choisissez une image JPG, PNG ou WebP de moins de 750 Ko.');return;}try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});set(key,data);}catch{setError('Impossible de lire cette image. Réessayez.');}};
  const asset=(key,label)=><div className="asset-editor"><div className="asset-preview">{form[key]?<img src={form[key]} alt={key==='logo'?'Aperçu du logo':'Aperçu de la photo'}/>:<><Image size={28}/><span>{key==='logo'?'Symbole de démonstration':'Sans photographie'}</span></>}</div><div><label className="file-label" htmlFor={`site-${key}`}>{label}</label><input id={`site-${key}`} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{upload(key,e.target.files[0]);e.target.value='';}}/><small>JPG, PNG ou WebP · 750 Ko maximum. Utilisez une image autorisée.</small>{form[key]&&<button type="button" className="text-button" onClick={()=>set(key,'')}><Trash size={16}/>Retirer l’image</button>}</div></div>;
  const restore=()=>{setForm(structuredClone(current));saved.current=JSON.stringify(current);setError('');setMessage('Version enregistrée rechargée.');};
  const submit=e=>{e.preventDefault();try{const result=onSave(form,form.version);const next=websiteContent(result);setForm(structuredClone(next));saved.current=JSON.stringify(next);guard.current=false;setError('');setMessage('Contenu enregistré. Le site de démonstration est à jour.');}catch(err){setError(err.message);}};
  return <><header className="page-heading"><div><p className="eyebrow">Votre vitrine</p><h1>Le site, à votre image.</h1><p>Modifiez votre contenu. La mise en page reste soignée.</p></div><button className="button secondary" onClick={()=>navigate('public')}>Voir le site <ArrowUpRight size={18}/></button></header>
    <div className="notice">Démonstration locale : les changements restent dans ce navigateur. Les coordonnées saisies seront affichées, sans déclencher d’appel ni d’envoi.</div>
    <div className="tabs content-tabs" role="tablist" aria-label="Contenu du site">{[['identity','Identité & contact'],['home','Accueil'],['faq','Questions fréquentes']].map(([id,label])=><button key={id} id={`tab-${id}`} role="tab" aria-selected={tab===id} tabIndex={tab===id?0:-1} onKeyDown={e=>{const ids=['identity','home','faq'];const index=ids.indexOf(id);let next;if(e.key==='ArrowRight')next=ids[(index+1)%3];if(e.key==='ArrowLeft')next=ids[(index+2)%3];if(e.key==='Home')next=ids[0];if(e.key==='End')next=ids[2];if(next){e.preventDefault();setTab(next);document.getElementById(`tab-${next}`)?.focus();}}} aria-controls="content-panel" onClick={()=>setTab(id)} className={tab===id?'active':''}>{label}</button>)}</div>
    <form onSubmit={submit} className="content-editor"><div id="content-panel" role="tabpanel" aria-labelledby={`tab-${tab}`}>
      {tab==='identity'&&<><h2>Les repères de votre centre</h2><p className="muted">Une identité cohérente sur le site et dans l’administration.</p><div className="form-grid">{field('name','Nom du centre',{max:70})}{field('signature','Signature',{max:80})}{field('location','Adresse / localisation',{max:200})}{field('phone','Téléphone',{required:false,hint:'Facultatif · coordonnées fictives pour les essais.'})}{field('email','Email',{required:false})}</div>{asset('logo','Importer un logo')}</>}
      {tab==='home'&&<><h2>Votre première impression</h2>{field('eyebrow','Texte d’introduction',{max:60})}{field('heroTitle','Titre principal',{area:true,max:140,hint:'Les retours à la ligne sont conservés sur grand écran.'})}{field('heroDescription','Présentation',{area:true,max:500})}{asset('heroImage','Importer une photo d’accueil')}{form.heroImage&&field('heroImageAlt','Description de la photo',{max:200})}{field('approachTitle','Titre de la section Notre approche',{max:120})}<div className="approach-edit-grid">{form.approach.map((item,i)=><fieldset key={i}><legend>Point {i+1}</legend><label htmlFor={`approach-title-${i}`}>Titre *</label><input id={`approach-title-${i}`} maxLength={80} required value={item.title} onChange={e=>set('approach',form.approach.map((a,j)=>j===i?{...a,title:e.target.value}:a))}/><label htmlFor={`approach-text-${i}`}>Description *</label><textarea id={`approach-text-${i}`} rows={3} maxLength={400} required value={item.text} onChange={e=>set('approach',form.approach.map((a,j)=>j===i?{...a,text:e.target.value}:a))}/></fieldset>)}</div></>}
      {tab==='faq'&&<><h2>Répondre avant le premier appel</h2><p className="muted">Des réponses courtes aux questions que votre équipe reçoit souvent.</p>{form.faq.map((item,i)=><fieldset className="faq-editor" key={i}><legend>Question {i+1}</legend><div className="field"><label htmlFor={`faq-question-${i}`}>Question *</label><input id={`faq-question-${i}`} maxLength={180} required value={item.question} onChange={e=>set('faq',form.faq.map((f,j)=>j===i?{...f,question:e.target.value}:f))}/></div><div className="field"><label htmlFor={`faq-answer-${i}`}>Réponse *</label><textarea id={`faq-answer-${i}`} rows={3} maxLength={800} required value={item.answer} onChange={e=>set('faq',form.faq.map((f,j)=>j===i?{...f,answer:e.target.value}:f))}/></div><button type="button" className="text-button" onClick={()=>set('faq',form.faq.filter((_,j)=>i!==j))}><Trash size={16}/>Retirer cette question</button></fieldset>)}{form.faq.length<8&&<button type="button" className="button secondary" onClick={()=>set('faq',[...form.faq,{question:'',answer:''}])}><Plus size={18}/>Ajouter une question</button>}</>}
    </div>{current.version!==form.version&&<p className="form-alert" role="alert">Une autre fenêtre a modifié le site. Rechargez la version enregistrée pour éviter d’écraser ses changements.</p>}{error&&<p className="form-alert" role="alert">{error}</p>}{message&&<p className="saved-message" role="status"><Check size={18}/>{message}</p>}
    <div className="content-savebar"><span>{dirty?'Modifications non enregistrées':'Contenu à jour'}</span><div><button type="button" className="button secondary" onClick={()=>{if(!dirty||confirm('Abandonner les modifications non enregistrées ?'))restore();}} disabled={!dirty&&current.version===form.version}>Recharger</button><button className="button primary" type="submit" disabled={!dirty}>Enregistrer <Check size={18}/></button></div></div></form></>;
}
